### ISSUE TITLE
deluxetable has extra row space at the end

### ISSUE THREAD

**Issue by lcmayor** [AASJournals/AASTeX60#11]
Using the following instructions:

\begin{deluxetable}{lrr}
\tablecolumns{3}
\tablewidth{0pt}
\tablecaption{\label{tbl:counts} Number of images in each filter.}
\tablehead{
\colhead{Filter} & \colhead{WAC} & \colhead{NAC}}
\startdata
VIO & 658 & \nodata \
BL1 & 201 & 426 \
\hline
Total & 3283 & 1714\
\enddata
\end{deluxetable}

The resulting table has nearly a whole extra row after the "Total" line. Preceding the commands with \floattable causes the table to then appear normally but in two column format spans both columns.

Am I missing something?

**Comment by gregschwarz** [comment]
This is the "normal" behavior but there are two issues. One is why is the \hline appearing below that last line and why does the addition of \floattable change the behavior. I will have to ask our latex programmer to look into this. As for the spanning two columns I do not see that when I use this text. I will send you an email offline so you can send me your latex to see if I can duplicate it.

Greg

**Comment by augustfly** [comment]
this sounds like the same problem I saw with \floattable allowing other elements to float inside the table float. do we have any resolution on it? 

if there is a \floattable problem with deluxetable then we should open a separate issue and close this one.

**Comment by augustfly** [comment]
@lcmayor @gregschwarz was this addressed by v6.1?

**Comment by gregschwarz** [comment]
Fixed in v6.1
