### ISSUE TITLE
\psj needed for Planetary Science Journal

### ISSUE THREAD

**Issue by joeharr4** [AASJournals/AASTeX60#111]
The new Planetary Science Journal needs \psj in aastex63.cls

Unrelated, on 
https://journals.aas.org/aastex-package-for-manuscript-preparation/
the release date for 6.3 is messed up.  Says "July 10 8, 2019", should say "October 8, 2019", I think.

--jh--

**Comment by augustfly** [comment]
Fixed in v6.3.1
