### ISSUE TITLE
Explicit support for software in bst

### ISSUE THREAD

**Issue by pqrs6** [AASJournals/AASTeX60#118]
I'm including a citation to pandas following the recommendation by the pandas development team (https://pandas.pydata.org/about/citing.html) and get the warning

```
BibTeX entry type for "pandas" isn't style-file defined
```

I think the warning comes from the fact that this is a `@software` type entry:
```
@software{pandas,
    author       = {{Pandas Development Team}},
    title        = {pandas-dev/pandas: Pandas},
    month        = feb,
    year         = 2020,
    publisher    = {Zenodo},
    version      = {latest},
    doi          = {10.5281/zenodo.3509134},
    url          = {https://doi.org/10.5281/zenodo.3509134}
}
```

I believe the correct format needs to be added by including a `software` function in `aasjournal.bst`. I'd make a suggested edit, but I'm not sure what the specific format for the bibliography that conforms to the AAS standard.

For what it's worth, this might not be an issue at all, since the bibliography itself looks like this for me:

![Screenshot from 2020-08-04 13-26-27](https://user-images.githubusercontent.com/6478137/89288568-27b61f80-d656-11ea-881f-e81c7d033128.png)

**Comment by augustfly** [comment]
Hi,

That's right. An unknown `bibtex` type drops back to `@misc` for aasjournal.bst, which treats any `@misc` basically like a versioned digital object (e.g., data or software). 

It was decided (with our input!) that Zenodo will publish `bibtex` types that match their implicit types even though most `bibtex` styles won't know what an `@software` type is.  This was to be more inline with [`biblatex`](https://ctan.org/pkg/biblatex?lang=en), which does recognize @software types. Of course the current `biblatex` `@software` type defaults to `@misc` styling as well. 

These circumstances could change in the future. If there's a cause to treat `@software` and `@misc` independently then will do the work to differentiate them. 

I hope this is okay!

**Comment by pqrs6** [comment]
Yes, thanks for clarifying! I was just wanted a perfectly clean LaTeX log and that one warning was bugging me.
