### ISSUE TITLE
line numbers not being generated until last equation

### ISSUE THREAD

**Issue by darthoctopus** [AASJournals/AASTeX60#131]
In paragraphs containing display math, line numbers are not being generated until after the final equation in the paragraph (see image for an example):

![Screenshot from 2021-07-17 13-51-18](https://user-images.githubusercontent.com/5761408/126045699-3fda57d2-e234-4e9d-9c4f-f493698ec224.png)

**Comment by gregschwarz** [comment]
This is due to a know problem between the lineno.sty and amsmath.sty packages. There are some work arounds for it and the latest version of AASTeX v6.3.1 has them. Please upgrade to that to confirm that the problem is solved.

https://journals.aas.org/aastex-package-for-manuscript-preparation/

**Comment by darthoctopus** [comment]
can confirm that aastex631 fixes the issue, thank you.
