### ISSUE TITLE
preprint style has lines that are too long

### ISSUE THREAD

**Issue by davidwhogg** [AASJournals/AASTeX60#14]
There are rules about how many characters / words there should be for a line to be readable, the preprint option violates them. See, eg, Bringhurst http://www.amazon.com/Elements-Typographic-Style-Robert-Bringhurst/dp/0881791326

**Comment by jradavenport** [comment]
👍 
This has been a stick in my craw forever with the preprint style.

**Comment by augustfly** [comment]
i/we is/are going to have to do some refinement on this to understand it better. i think you mean the lines are overflowing the right hand margin. 

btw do you know if Bringhurst has a github handle?

**Comment by davidwhogg** [comment]
No, I don't mean that it is formatted wrong technically. I mean that no line should be longer than some number of "em"s or characters, or else it is hard for humans to scan without line-skip errors.

**Comment by augustfly** [comment]
Thanks, @davidwhogg, now I understand. It also helps me understand my dislike of preprint layout up to now.

Clearly relates to #16  though 12pt font may not be enough of a fix. There are a number of ways to target a maximum line length once we knowingly pick a maximum line length.

**Comment by davidwhogg** [comment]
Agreed! Here's a consideration: You open a PDF file on a phone and read it on-screen. That strongly suggests 12 pt and lines that are no longer than about 6.5in (even that's getting long). You could do 10pt and lines that are no longer than 5.5in, but then you are wasting white space on that phone screen.

**Comment by augustfly** [comment]
Thanks, David. We are definitely thinking about mobile and single column formats for HTML and PDF content and layout.

**Comment by jradavenport** [comment]
I think it's useful to bring the `# of characters per line` (back) in as a metric to consider, not just the physical scale in inches or point size. Something between [40 and 80 char per line](https://en.wikipedia.org/wiki/Line_length) on average is good, which is the problem the single-column and preprint formats violate.

At .astro6 I [mocked up](https://github.com/jradavenport/elevate-apj) what a single column version of the journal format might look like, and I wonder if AASTeX60 could go for something [like this](https://github.com/jradavenport/elevate-apj/blob/master/flares.pdf)?

**Comment by augustfly** [comment]
right & I agree. i love the width and font size of this mockup. I'm really hoping that we can at least get font declarations back into the AASTeX v6.1, and narrow the default page width for single column preprint PDFs.   

the problem with unpaginated PDF is that it only solves part of the problem with PDF, namely, pagination. i've been reading up on the accessibility issues in PDF and the ability (or not) to resize/reflow PDF material. I'm not sure I know yet what that requires in terms of authoring tools like LaTeX.

**Comment by augustfly** [comment]
I'll just leave this here to say thank you. 

https://github.com/dfm/peerless/blob/master/document/ms.tex#L19-L69

**Comment by davidwhogg** [comment]
You are doing god's work, @augustfly

**Comment by god** [comment]
@augustfly can do anything through @god who strengthens him.

**Comment by augustfly** [comment]
i'm pretty sure it's anything through @knuth but whatevs :)

**Comment by god** [comment]
And so I tell you, every kind of sin and slander can be forgiven, but blasphemy against the Spirit will not be forgiven @augustfly.

**Comment by augustfly** [comment]
I guess I'll take my chances with Donald, @god.  

And, no, not **that** Donald, the literate one.

**Comment by augustfly** [comment]
@davidwhogg i believe the addition of the `modern` style in v6.1, which is based upon the modifications you and Dan developed, provide a solution to this issue.

**Comment by davidwhogg** [comment]
yes!
