### ISSUE TITLE
Acknowledgement enviroment spills over page margins

### ISSUE THREAD

**Issue by Bovornpratch** [AASJournals/AASTeX60#144]
Hi,

I'm preparing a paper draft using AAStex 6.3.1. My current acknowledgment text spills over the page when using the new  acknowledgment environment (see image attached). Shortening the Acknowledgement is not possible as it is a required text.  Placing the whole \begin{acknowledgements} in curly brackets does not work for me {}

![image](https://user-images.githubusercontent.com/20829556/163348013-8dbefc3d-5143-40fc-adb2-fcf3b59f0394.png)

I created a dummy overleaf file with similar structure to my draft which reproduces the issues under this link.
https://www.overleaf.com/9615757623kgbtksnjdxph 

PS. I have saw the solution for overlapping \software and \begin{acknowledgements}. Moving software into acknowledgement seems to work for me but I can not confirm since it spills over the bottom margin too.

**Comment by gregschwarz** [comment]
This is a bug within the acknowledgment environment. The solution is to not use it. It is only needed when the "anonymous" command is used for dual anonymous (DAR) review. When "anonymous" is used the contents inside the acknowledgment environment are suppressed. If you are not using DAR there is no need for it. Just type in your acknowledgments or if you really want a section header insert "\section{Acknowledgments}" and you should not have any problems.
