### ISSUE TITLE
12-pt style for preprint

### ISSUE THREAD

**Issue by davidwhogg** [AASJournals/AASTeX60#16]
Every thing I have ever put on arXiv has been preprint style, but 12 pt. That's no longer possible? I would be fine with this if it didn't violate rules in Bringhurst. http://www.amazon.com/Elements-Typographic-Style-Robert-Bringhurst/dp/0881791326

**Comment by augustfly** [comment]
to whit  “By all means break the rules, and break them beautifully, deliberately and well.” -- Bringhurst

though I can't claim we break them with any of those characteristics. 

this one seems fairly clearly stated.

**Comment by gregschwarz** [comment]
v6.1 has some different style options.  The default is a single column, single spaced, 10 point font style while the other options are:

twocolumn =	10 point font in a single spaced, two column style.
preprint = Same as the default except with 12 point font.
preprint = Same as twocolumn except with 12 point font.
modern = a stylish, single column, 12 point font, article with wider left and right margins. This uses the Daniel Foreman-Mackey and David Hogg design
manuscript = 12 point font in a double spaced, single column style.

**Comment by augustfly** [comment]
I think there is a tiny bug in your description: 

> preprint2 = Same as twocolumn except with 12 point font.

**Comment by gregschwarz** [comment]
Yes, I accidentally deleted the "2" from the second "preprint" line. It should be 

preprint2 = Same as twocolumn except with 12 point font.
