### ISSUE TITLE
default columnness

### ISSUE THREAD

**Issue by augustfly** [AASJournals/AASTeX60#21]
I don't understand why we switched the default behavior of emulateapj from two column to one column. 

\documentclass{emulateapj}  => defaults to 2 column
\documentclass{aastex6} => defaults to 1 column

**Comment by gregschwarz** [comment]
Two reasons. One, the default of v5.2 is single column so there is symmetry there. Two, I want people to write their latex in single column and opt in to double column since that is what we want authors to be used to as we transition to more web-centric platforms.

**Comment by jradavenport** [comment]
Just a note that this directly relates back to #14 

I think pushing people towards a web-centric, single column format is good. But encouraging people towards line lengths that are too long (and thus harder to read)

**Comment by augustfly** [comment]
Please note that addition of the `modern` style in v6.1, which is based on AASTeX mods by Dan Foreman-Mackey and David Hogg. `modern` achieves 12pt, narrower, single column with larger lineskips and other nice modifications.
