### ISSUE TITLE
Zenodo Bibtex record not shown properly in References

### ISSUE THREAD

**Issue by michaelaye** [AASJournals/AASTeX60#22]
I have this Zenodo DOI project here:
https://zenodo.org/record/51824#.V0Is5lesSAY
with a Bibtex record like this (as produced by that page):

```bibtex
@misc{k_michael_aye_2016_51824,
  author       = {K.-Michael Aye},
  title        = {pyciss: v0.3.2},
  month        = may,
  year         = 2016,
  doi          = {10.5281/zenodo.51824},
  url          = {http://dx.doi.org/10.5281/zenodo.51824}
}
```
and the aastex.bst together with AASTex 6 makes this out of it:

Aye, K.-M. 2016, pyciss: v0.3.2, , , doi:10.5281/zenodo.51824

Your instructions here:
http://journals.aas.org/policy/software.html
say:

> Citing a DOI for the software, for example, obtained via Zenodo or FigShare (e.g. Foreman-Mackey et al. 2014, corner.py, v0.1.1, Zenodo, doi:10.5281/zenodo.11020, as developed on GitHub)

From this it looks like that Bibtex should interpret an actual `version` field, because it is separated from the project title, plus it has a `Zenodo` item that is not even procuded by the Zenodo Bibtex record exporter. Are these the 2 missing items indicated by the three commas in what is currently being made out of my current BibTex entry? What are the field names for that so that I could hot-fix my record on my own.
Maybe this should be solved together with Zenodo so that their BibTex exporter matches more closely the requirements of AASTex? Alternatively, AASTex could support BibLatex that supports more kinds of online citations with more options, IIRC.

**Comment by augustfly** [comment]
hi,

yes, to confirm, it is necessary to make at least 2 edits to the Zenodo bibtex to make it match our preferred style. these are to parse out the version, and to add the publisher. It should look like:

```
@misc{k_michael_aye_2016_51824,
  author    = {K.-Michael Aye},
  title     = {pyciss}
  version   = {0.3.2},
  publisher = {Zenodo},
  month     = may,
  year      = 2016,
  doi       = {10.5281/zenodo.51824},
  url       = {http://dx.doi.org/10.5281/zenodo.51824}
}

```

See also: http://journals.aas.org/authors/aastex/aasguide.html#softwareandthirdparty
