### ISSUE TITLE
add options to hide specific edits

### ISSUE THREAD

**Issue by GitatHub** [AASJournals/AASTeX60#24]
\turnoffedit will disable all highlights including \edit1, \edit2 and \edit3.
However, in a normal submission process, we always need to hide \edit1 when submitting revision 2.
It is also required to hide \edit2 when submitting revision 3.
If the edits can not be hidden according to revision phases, I do not think this feature is better than traditional \textbf

**Comment by gregschwarz** [comment]
Our latex programmer is working on V6.1 right now. We will see if we can incorporate this into the next release.

**Comment by GitatHub** [comment]
where to get v6.1? I did not find it either on github or aas.org

**Comment by gregschwarz** [comment]
Our programmer is still working on V6.1 now. We are not sure when the official release will be but it will be this summer. When it is ready it will be posted here and on the AAS site.

**Comment by augustfly** [comment]
v6.1 (https://github.com/AASJournals/AASTeX60/commit/f888b19ddaa5373790134df8fcf091de9adf622e) appears to solve this issue by adding commands to control individual edits. From the [updated documentation](http://journals.aas.org/authors/aastex/aasguide61.html#revised_color):

>in AASTeX v6.1 the \turnoffeditone, \turnoffedittwo, and \turnoffeditthree commands are introduced to control which specific revision mark is repressed. The \turnoffediting command will repress all of the text mark with any \edit command.
