### ISSUE TITLE
Deluxetable in Appendix causes it to revert to two-column mode

### ISSUE THREAD

**Issue by pkgw** [AASJournals/AASTeX60#25]
I have an appendix that is in single-column mode. If I include a deluxetable, all of the text beyond it shows up in two-column mode instead. Not exactly the biggest deal, but it looks a bit weird and is presumably not intended.

**Comment by gregschwarz** [comment]
Can you post a screenshot of the appendix and email me <greg.schwarz@aas.org> the latex you used? Our latex programmer is working on bugs in v6.0 for v6.1 right now so this would be a good time to address this issue.

**Comment by pkgw** [comment]
Will do. Here's a screenshot:

![screenshot from 2016-07-25 14-13-06](https://cloud.githubusercontent.com/assets/59598/17111989/f81ec4dc-5271-11e6-92fd-52fd9da4c664.png)

**Comment by gregschwarz** [comment]
Interesting bug. I will forward it on to our programmer.

**Comment by pkgw** [comment]
Oh, this doesn't happen if I use the plain `deluxetable` environment rather than `deluxetable*`. I'd say that the behavior is still not desirable, though, and I believe that using a starred environment in a single-column mode is something that's supposed to be fine to do.

**Comment by gregschwarz** [comment]
Ah, this is useful information to have. It should help her get to the root of the problem quicker.

**Comment by gregschwarz** [comment]
According to our Latex programmer deluxetable* should only be used for 2 column modes (as the * tells it to span two columns). Use plain deluxetable for single column tables.

**Comment by augustfly** [comment]
Hi @pkgw and @gregschwarz -- is this considered solved or not? I'm not clear if this is a documentation issue or bug.

**Comment by gregschwarz** [comment]
Yes, this has been fixed in v6.1
