### ISSUE TITLE
Title footnotes

### ISSUE THREAD

**Issue by andycasey** [AASJournals/AASTeX60#26]
In previous AASTeX versions one was able to include a footnote in the title. An example might be including the [obligatory](http://www.lco.cl/telescopes-information/magellan/science-results-images/magellan-attribution) 'This paper includes data gathered with the 6.5 meter Magellan Telescopes located at Las Campanas Observatory, Chile'. In version 6.0 the footnote doesn't render. Is this intentional? Is there a new recommended way to include a footnote like this? Or is this "bad practice" that AASTex v6+ is trying to stamp out?

**Comment by gregschwarz** [comment]
It is a known bug and our latex programmer is working on a fix for v6.1 which should come out later this summer.

**Comment by andycasey** [comment]
That was quick! Thanks @gregschwarz.

**Comment by gregschwarz** [comment]
The power of github and instant notification. Sorry I do not have a temporary solution for you right now.

**Comment by andycasey** [comment]
Closing this issue because title footnotes work as expected in v6.1 -- thanks!
