### ISSUE TITLE
deluxetable cannot span multiple pages

### ISSUE THREAD

**Issue by mrawls** [AASJournals/AASTeX60#3]
Any `deluxetable` or `deluxetable*` containing more rows than can fit on one page will run off the bottom of the page rather than break and continue on the next page. Neither `\LongTables` nor `\tablebreak` seem to fix this behavior. Also see [this relevant twitter conversation](https://twitter.com/merrdiff/status/695003129251651584).

**Comment by gregschwarz** [comment]
Unfortunately the functionality that allows deluxetable to break over multiple pages (i.e. longtable) was stupidly dropped in v6.0. Our latex expert is currently working on a solution that brings page breaks back to deluxetable while still allowing all the new features to work.  This requires a careful reintegration of longtable back into the classfile.  We hope to have a fixed version ready by next week which will be posted here, on the new AASTeX site and CTAN. We apologize for the inconvenience.

**Comment by mrawls** [comment]
Thanks for the prompt response! Glad to hear you are working on a quick fix.

**Comment by augustfly** [comment]
This should be fixed in #7.
