### ISSUE TITLE
amsmath matrix 

### ISSUE THREAD

**Issue by AlexGKim** [AASJournals/AASTeX60#30]
When using amsmath matrix, there is an error "Missing number, treated as zero."  Here is an example that has the problem.  Note that aastex works fine.

\documentclass{aastex6}
\usepackage{amsmath}
\begin{document}
 \begin{equation}
\begin{pmatrix}
1.000 & 0.624 & -0.318 & -0.287 \
0.624 & 1.000 & -0.180 & 0.104 \
-0.318 & -0.180 & 1.000 & 0.629 \
-0.287 & 0.104 & 0.629 & 1.000
  \end{pmatrix}.
 \end{equation}
\end{document}

**Comment by gregschwarz** [comment]
You need to put "\cr" at the end of each line, e.g.

\documentclass{aastex61}                                                        
\usepackage{amsmath}                                                            
\begin{document}                                                                
                                                                                
\begin{equation}                                                                
\begin{pmatrix}                                                                 
1.000 & 0.624 & -0.318 & -0.287 \cr                                             
0.624 & 1.000 & -0.180 & 0.104 \cr                                              
-0.318 & -0.180 & 1.000 & 0.629 \cr                                             
-0.287 & 0.104 & 0.629 & 1.000                                                  
\end{pmatrix}                                                                   
\end{equation}                                                                  
                                                                                
\end{document} 

Should work fine then.

**Comment by augustfly** [comment]
You may want to clarify @gregschwarz that this works in 6.0 and the unreleased 6.1 mentioned in your snippit. :)

**Comment by AlexGKim** [comment]
Thanks for the quick response.  I have added the \cr as recommended and the same error persists,

! Missing number, treated as zero.
<to be read again> 
                   c
l.5 \begin{pmatrix}

Here is my revised document

\documentclass{aastex6}   
\usepackage{amsmath}
\begin{document}
 \begin{equation}
\begin{pmatrix}
1.000 & 0.624 & -0.318 & -0.287 \cr
0.624 & 1.000 & -0.180 & 0.104 \cr
-0.318 & -0.180 & 1.000 & 0.629 \cr
-0.287 & 0.104 & 0.629 & 1.000
  \end{pmatrix}.
 \end{equation}
\end{document} 

Here is the version of amsmath I am using.
42:gerard akim$ grep amsmath test.log 
(/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsmath.sty
Package: amsmath 2013/01/14 v2.14 AMS math features

I also get the curious message

(/Users/akim/Library/texmf/tex/latex/aastex6.0/aastex6.cls

LaTeX Warning: You have requested document class `aastex6',
               but the document class provides `aastex'.

**Comment by gregschwarz** [comment]
That last warning is a stupid bug in the classfile that does not affect anything and has been fixed in the next version.  

As for the other issue with the pmatrix, in the beta version of AASTeX v6.1 that we are currently testing there is no error message and it compiles fine. It is only with v6.0.

[mathtest.pdf](https://github.com/AASJournals/AASTeX60/files/485726/mathtest.pdf)

If you email me directly at greg.schwarz@aas.org I will send you a copy of the beta to try out.

**Comment by augustfly** [comment]
Could we confirm/deny that this is fixed in v6.1?

**Comment by augustfly** [comment]
I have tested the code provided by @AlexGKim above with v6.1 released and confirm that this and many other AMS math matrix examples now work. Closing.
