### ISSUE TITLE
Affiliation formatting style

### ISSUE THREAD

**Issue by kadrlica** [AASJournals/AASTeX60#34]
The AAS journals center the affiliations for authors, and it was possible to mimic this behavior with emulateapj. For example, see the ApJ and emulateapj versions of the paper below:
* ApJ: http://iopscience.iop.org/article/10.1088/0004-637X/808/1/95/pdf
* emulateapj: https://arxiv.org/pdf/1504.02889v2.pdf

Compare with the version using `aastex61`:
* aastex61: [aastex61_example.pdf](https://github.com/AASJournals/AASTeX60/files/666832/aastex61_example.pdf)

It appears that with `aastex61` the affiliations are centered with the `longauthor` option, but not in the default `twocolumn` format.  I'm going to look into a style adjustment to center affiliations in `twocolumn` format, and any suggestions that point me the right direction would be appreciated.

**UPDATE**
On further examination, I actually think that affiliations should be centered for all document styles (e.g., `manuscript`,`preprint`, `preprint2`,`modern`, and `twocolomn`). I would also argue that the vertical space between the author list/collaboration tag is too large compared to ApJ style. Similarly, the space between the title and author list is larger than the ApJ (or emulateapj) equivalent.

Comments from @davidwhogg, @dfm, @augustfly, @gregschwarz especially welcome.

**Comment by augustfly** [comment]
@kadrlica thanks for this issue and look forward to what you find. i know there have been other questions posted elsewhere about the styling of affiliations, but @gregschwarz would know about those.

**Comment by kadrlica** [comment]
Ok, the offending lines are [here]:(https://github.com/AASJournals/AASTeX60/blob/2743ae241f5bb9e3b9651439c1cbfa56b0d58d29/cls/aastex61.cls#L768-L774)
```
\def\frontmatter@affiliationfont{\normalfont\footnotesize\it
\ifmodern\baselineskip=14pt\fi
\iflongauthor\else
\rightskip-12pt plus 1fil
\leftskip6pt \parindent-4pt
\fi
}%
```
In particular, the `\rightskip` and `\leftskip` are getting rid of the center format. A minimally invasive change would be:
```
\def\frontmatter@affiliationfont{\normalfont\footnotesize\it                         
\ifmodern\baselineskip=14pt\fi                                                       
\iflongauthor\else                                                                   
\iftwocolstyle\else                                                                  
\rightskip-12pt plus 1fil                                                            
\leftskip6pt \parindent-4pt                                                          
\fi\fi                                                                               
}%
```
However, I would argue that centering of affiliations should be done for all styles *except* `modern`. Therefor, my preferred change would be:
```
\def\frontmatter@affiliationfont{\normalfont\footnotesize\it                         
\ifmodern
\baselineskip=14pt
\rightskip-12pt plus 1fil                                                            
\leftskip6pt \parindent-4pt   
\fi                                                                                
}%

**Comment by kadrlica** [comment]
Here's my example centering and tightening the affiliations. I've tried not to touch the `modern` style, since I'm not sure what it's authors want. I'll create a pull request with these changes.

Old aastex61 affiliation formatting: [aastex61_example.pdf](https://github.com/AASJournals/AASTeX60/files/667261/aastex61_example.pdf)
Tighter centered affiliation formatting: [aastex61_new_example.pdf](https://github.com/AASJournals/AASTeX60/files/667262/aastex61_new_example.pdf)

**Comment by augustfly** [comment]
@gregschwarz is this on our list for 6.2?

**Comment by gregschwarz** [comment]
It is not but I will add.
