### ISSUE TITLE
known "hidden file" bug in linux for v6.1

### ISSUE THREAD

**Issue by augustfly** [AASJournals/AASTeX60#35]
See: http://journals.aas.org/authors/aastex/linux.html

For users on Linux operating systems, one change in v6.1 will cause problems on compilation. A hidden ".bib" file is created in v6.1 but the default behavior LaTeX on Linux is to not allow any files to be written that begin with a period. This is not a problem on Windows or Mac operating systems. There are two work arounds available until this bug is fixed.

- Comment out these lines in aastex61.cls
>  %% get rid of \jobname Notes being sent to .aux file:
>  \let\bibdata@app\relax
>  \def\pre@bibdata{}

- Change the command line compiler call to allow a "." file by passing the environmental variable `openout_any=a`
> openout_any=a pdflatex file

**Comment by augustfly** [comment]
This is known to break arXiv submissions if not fixed as reported by @hippke

**Comment by GitatHub** [comment]
waiting for the fix. this is annoying ....

**Comment by augustfly** [comment]
@GitatHub the fix is in the comment above (remove those lines from the classfile), and is now in the released version at our [main AASTeX website ](http://journals.aas.org/authors/aastex.html). A patch will be deployed here tonight. We don't know how long it will take for arXiv to pick up the patch though.

**Comment by augustfly** [comment]
Fixed in https://github.com/AASJournals/AASTeX60/commit/2743ae241f5bb9e3b9651439c1cbfa56b0d58d29.
