### ISSUE TITLE
Allowing manuscript text to start on page 1

### ISSUE THREAD

**Issue by iancze** [AASJournals/AASTeX60#38]
First, thanks for the nice fixes in v6.1. With this new version it seems as though I am unable to get my document text (other than author and abstract information) to actually start on page 1, regardless of how short the abstract is. This happens with the default, twocolumn, and modern styles. Is this intentional?

I've attached an example.
[main.pdf](https://github.com/AASJournals/AASTeX60/files/620857/main.pdf)

Latex here: https://gist.github.com/iancze/e26d3b3ea833cb97d601dc8455fcf382

Thanks!

**Comment by gregschwarz** [comment]
Yes, this is intentional. All the front matter in v6.1 has its own page. The main text does not begin until that is done. If the front matter is short this is page 2. If it a long author list it could be page 3.

**Comment by ngoldbaum** [comment]
I'd prefer to have the main text start on page 1.

**Comment by gregschwarz** [comment]
We will add an option for this in the next bug fix release.

**Comment by augustfly** [comment]
Related twitter conversation that probably brought @ngoldbaum over, including my speculation on the causes:

https://twitter.com/astrocrash/status/806154803135074305

**Comment by guillochon** [comment]
This is a pretty illogical change in my opinion, it's not clear that the AAS journals themselves even want the abstract on a separate page (checking the December ApJ it appears that all the papers there still start the main text on page 1), and it looks awful for shorter abstracts, in my opinion.

Could this be at least made optional? I'll revert to 6.0 for the time being.

**Comment by kadrlica** [comment]
I agree with @guillochon. The default should be for the main text to start on the first page (if possible). If it is desirable to preserve the ability to have the frontmatter on it's own page, then that should be added as an optional argument.

**Comment by kadrlica** [comment]
I've been trying to hack my way around this, and it looks like I've got something working...

* Reinstate the previous vertical space formatting in `finalspace`:  [Line 776](https://github.com/AASJournals/AASTeX60/blob/2743ae241f5bb9e3b9651439c1cbfa56b0d58d29/cls/aastex61.cls#L776)
* Remove two instances of `\clearpage` for the first section: [Line 999](https://github.com/AASJournals/AASTeX60/blob/2743ae241f5bb9e3b9651439c1cbfa56b0d58d29/cls/aastex61.cls#L999), [Line 6208](https://github.com/AASJournals/AASTeX60/blob/2743ae241f5bb9e3b9651439c1cbfa56b0d58d29/cls/aastex61.cls#L6208)

Here's the branch where I've hacked this, but no guarantees that it works:
https://github.com/kadrlica/AASTeX60/blob/firstpage/cls/aastex61.cls

**Comment by kadrlica** [comment]
@augustfly and @gregschwarz any chance to take a look at the branch? Should I submit a pull request or is there a milestone for adding this option? This (coupled with the pending PR #42) is preventing me from broadly adopting aastex61.

**Comment by augustfly** [comment]
@kadrlica We really appreciate this input and PR #42 . We are currently collect items, bugs and feature requests, to pass onto our latex contractor (who isn't on github) for our next round of updates. I think the best course of action we can take is to milestone your fix for v6.2. Alternatively @gregschwarz and I could discuss accepting this PR now as a patch release and trying to ensure we don't get a bork when we fund the next round of edits.

**Comment by lcjohnso** [comment]
@augustfly I wanted to voice support for PR #42.  I just discovered this thread (thanks @kadrlica!) and plan to start using the updated/edited version of the stylefile immediately -- I imagine I'm not alone.  Do you have an ETA for PR #42 acceptance or rollout of v6.2?

**Comment by augustfly** [comment]
@gregschwarz is this on our list for 6.2? I want to tag/milestone in the ones that are so we can let folks know what is happening.

**Comment by gregschwarz** [comment]
Yes it is.

**Comment by cmccully** [comment]
@kadrlica I really like your updates. 👍  
Would it be possible to shrink the width and center the abstract like emulateapj (e.g. https://www.sharelatex.com/templates/journals/emulateapj). Thanks for your work on this!

**Comment by kadrlica** [comment]
@cmccully that might be possible, but it's probably the topic for another issue. Want to create one?
