### ISSUE TITLE
bibtex style file picking up "note" field

### ISSUE THREAD

**Issue by augustfly** [AASJournals/AASTeX60#44]
The release version of `aasjournal.bst` picks up the "note" field in `@misc` and `@article` bibtex entries and appends the note text to the end of the compiled `\bibitem`. 

**This is unwanted behavior**.

The work around is to hand edit the compiled `bbl` file to remove the note text or to edit the source bibtex to remove the note field or rename the "note" key to something else, e.g, `adsnote`, or `zenodonote`.

**Comment by michaelaye** [comment]
Alternatively (if the `bbl` file is large, it might be faster and/or easier to use https://bibtexparser.readthedocs.io/
