### ISSUE TITLE
 \turnoffedit OR \turnoffeditone does not work as expected

### ISSUE THREAD

**Issue by GitatHub** [AASJournals/AASTeX60#46]
They do not remove the color of the text, but just remove the text included in the braces...
eg, "I am a \edit1{robot}."  becomes "I am a ." in the final PDF.
if \turnoffedit or \turnoffeditone

and there is always an unwanted huge space after each \edit1{}, sometimes it even makes a \par effect..

**Comment by gregschwarz** [comment]
Thank you. This is a known bug and will be fixed in the next release.
