### ISSUE TITLE
Displaying preprint numbers?

### ISSUE THREAD

**Issue by kadrlica** [AASJournals/AASTeX60#48]
Many institutions require the inclusion of internal preprint or report numbers. In `revtex4-1`, this is performed using the `\preprint` command and the document class option `preprintnumbrs` (documented in Section 9.2.5 of the [revtex4-1 docs](http://mirror.utexas.edu/ctan/macros/latex/contrib/revtex/doc/latex/revtex/source/revtex4-1.pdf)).

Is there any equivalent in aastex6.1? The `\preprint` command and `preprintnumbers` options appear to be defined (at least I don't see an error during compilation), but nothing is displayed in the output. Below is a minimal working example:
```
\documentclass[preprint,preprintnumbers]{aastex61}
\begin{document}
\preprint{REPORT-123}
\title{Hello World}
\begin{abstract}
Hello world!
\end{abstract}
\section{Introduction}
Introducing ... hello world!
\end{document}
```

**Comment by gregschwarz** [comment]
There is nothing equivalent to this but you could use the watermarking commands to put this information on the first page,

http://journals.aas.org/authors/aastex/aasguide61.html#title_page

Would that do the trick?

Greg Schwarz
AAS Journals Data Editor

**Comment by kadrlica** [comment]
Thanks Greg, but this isn't what I want. Here's an example of what `\preprint` command should do.
![example](https://cloud.githubusercontent.com/assets/5605123/26479782/77698434-419b-11e7-9f3a-a01d213d4296.png)
The code for generating this is here:
```
```

**Comment by augustfly** [comment]
@gregschwarz I don't see our contractor wanting to import a new package, but she may be able to mimic the side/cut-in/running heads to place this on the title page. 

fwiw emulateapj, which aastex6.1 is based upon, totally rewrites the revtex4-1 front matter building, which means the \preprint{} data never has a chance to be instantiated and added. It is silently ignored.

**Comment by kadrlica** [comment]
I agree that working with the existing facility in revtex4-1 is much preferred to the hack I posted.

**Comment by augustfly** [comment]
@gregschwarz Since this is a case of `emulateapj` silently overwriting `revtex4-1` functionality (`\preprint`), then I'd have Amy take a look during v6.2.
