### ISSUE TITLE
Shrink abstract width?

### ISSUE THREAD

**Issue by kadrlica** [AASJournals/AASTeX60#52]
@cmccully suggests shrinking the width and center the abstract like emulateapj (e.g. https://www.sharelatex.com/templates/journals/emulateapj). This was originally proposed in #38, but is better kept in a separate issue.

@augustfly was this slated for [v6.3](https://github.com/AASJournals/AASTeX60/milestone/2)?

**Comment by augustfly** [comment]
thanks for pulling this out into a separate issue, @kadrlica .  

it should be [v6.2](https://github.com/AASJournals/AASTeX60/milestone/1) (turns out that relabeling a milestone after you can't count isn't a seamless as I would have thought).

**Comment by cmccully** [comment]
Thanks for opening this issue @kadrlica. Any word on this? I'm afraid I don't really even know where to start to address this myself.

**Comment by pcubillos** [comment]
Hi all, this hack worked for me (taken from aastex v6.0):
```
\def\abstractname{ABSTRACT}
\long\def\frontmatter@abstractheading{%
 \begingroup
  \centering
  \abstractname
  \vskip 1mm
  \par
 \endgroup
 % :::: HACK: set width of abstract ::::
 \everypar{\rightskip=0.5in\leftskip=\rightskip}\par
}%
```

**Comment by kadrlica** [comment]
Thanks @pcubillos! I've created a pull requested based off of your hack from aastex v6.0. @cmccully you might be interested in this. @augustfly any word on when v6.2 is due?

**Comment by cmccully** [comment]
Thanks @kadrlica. I am indeed using the newest version. Thanks!
