### ISSUE TITLE
deluxetable \startlongtable only flows to multiple pages if table is in main body

### ISSUE THREAD

**Issue by mtbannister** [AASJournals/AASTeX60#54]
A deluxetable preceded with \startlongtable does not correctly generate all the pages of its table if the table is placed after the \bibliography{references} command, e.g when a table is in an Appendix. It only generates the first page, which has the correct "Table n continued" footer printed; but the rest of the table pages are not in the pdf.

**Comment by augustfly** [comment]
@mtbannister I am super sorry for the delayed reply. We appreciate the bug report! And it has been queued into v6.2 fixes.
