### ISSUE TITLE
Cross-references to figures in appendix jump to wrong figures

### ISSUE THREAD

**Issue by j6626** [AASJournals/AASTeX60#55]
Hi, 

I seem to be running into an issue where trying to reference a figure in the appendix will jump instead to the corresponding figure in the main text, i.e. if I have a figure B1 in the appendix with some label \label{fig:labelforB1}, then "Figure \ref{fig:labelforB1}" will correctly compile as "Figure B1," but the actual hyperlink jumps to Figure 1 instead.

**Comment by gregschwarz** [comment]
I have not heard of this behavior before. Can you send me a copy of your latex manuscript <greg.schwarz@aas.org> so I can check out the problem and see if it is exists for all the recent AASTeX flavors?

**Comment by augustfly** [comment]
often deleting *.aux fixes things like this.

**Comment by gregschwarz** [comment]
This is a bug in aastex6.cls. The best solution is to upgrade to aastex61.cls.
