### ISSUE TITLE
startlongtable not respecting table centering rules in deluxetable.

### ISSUE THREAD

**Issue by augustfly** [AASJournals/AASTeX60#56]
From: https://tex.stackexchange.com/questions/393150/centering-a-very-wide-deluxetable

There appears to be a bug in the \startlongtable that prevents the normal behavior of deluxetable to center the table and overflow both the left and right margins equally. I can show it to be independent of style (tested for modern and preprint).

**Comment by gregschwarz** [comment]
Added to the bug list.
