### ISSUE TITLE
twocolumn/text out of bounds

### ISSUE THREAD

**Issue by pcubillos** [AASJournals/AASTeX60#57]
Hi,

I'm having problems keeping hyphenated words, inline equations, and hyperlinks within the boundaries of the column (at least when using the twocolumn option) for AASTeX v6.1.
I haven't seen this happening in v6.0/preprint2, so it seems to be something related to v6.1.

Here's a minimal example:

``` latex
\documentclass[tighten, times, twocolumn]{aastex61}
\begin{document}

\title{A bug report using aastex v6.1}
\author{Patricio}

\section{Introduction}

This is a normal piece of text showing the length of a column,
everything is good so far.  Actually, many thanks to everyone in the
the AASTeX developer team.

However, sometimes the twocolumn option misses hyphenated-word boundaries.

Some inline equations also break, e.g., $\gamma=0.071
(T/2000)^{-0.7}$ cm$^{-1}$ atm$^{-1}$.
\end{document}
```
And here's the output: http://geco.oeaw.ac.at/patricio/subdir/aastex/sample61.pdf

**Comment by augustfly** [comment]
@pcubillos thanks for the report. there's definitely something weird with intra-line spacing and respecting margins that needs to be diagnosed. your minimum working example is great.
