### ISSUE TITLE
two deluxe longtables in a row

### ISSUE THREAD

**Issue by chukus** [AASJournals/AASTeX60#60]
I have two tables in a manuscript, both contain about 90 lines. I am using deluxetable* and
both have to span multiple pages so I used \startlongtable
before each. 

I put both tables after the references 

The first table works nicely, spans over 3 pages. The second one gets cut on page2
and does not show the third page with the last 22 lines. 
I see no obvious error in the compiler.... I triple checked all lines have all columns included...

**Comment by augustfly** [comment]
Can you compare this to the report in #54 @chukus?

**Comment by chukus** [comment]
I see they are very similar, yes.

**Comment by chukus** [comment]
AH!! magic!! Witchcraft! Put ackwnowledgements, references etc after the tables and voila.

**Comment by augustfly** [comment]
Great Carlos. We have a bug fix in the works for that one. I'll leave this open and we can try to close it when v6.2 is released.
