### ISSUE TITLE
tablehead centering with deluxetable

### ISSUE THREAD

**Issue by kadrlica** [AASJournals/AASTeX60#63]
It seems that `deluxetable` isn't centering the final column header and unit properly in the last table column. This is only really noticeable with short column headers, and centering is restored by adding a line break after the unit for the last column (but then you have an extra line break...).

![miscenter_example](https://user-images.githubusercontent.com/5605123/33799549-a431e81e-dcf3-11e7-82d9-5bd5a5d304e9.png)

Which results from this tex file:
```
\documentclass{aastex61}
\begin{document}

\begin{deluxetable*}{l ccccc }
\tablecolumns{13}
\tablewidth{0pt}
\tabletypesize{\footnotesize}
\tablehead{
Name & $x_1,y_1,z_1$ & $x_2,y_2,z_2$ & ${\rm R_{GC}}$ & col \\
 & (kpc) & (kpc) & (kpc) & (deg) 
}
\startdata
Data Goes Here     & \ldots  & \ldots & \ldots & \ldots \\
\enddata
\end{deluxetable*}

\begin{deluxetable*}{l ccccc }
\tablecolumns{13}
\tablewidth{0pt}
\tabletypesize{\footnotesize}
\tablehead{
Name & $x_1,y_1,z_1$ & $x_2,y_2,z_2$ & ${\rm R_{GC}}$ & col \\
 & (kpc) & (kpc) & (kpc) & (deg) \\
}
\startdata
Data Goes Here     & \ldots  & \ldots & \ldots & \ldots \\
\enddata
\end{deluxetable*}

\vfill Fill space ...
\clearpage
\end{document}
```

**Comment by augustfly** [comment]
@kadrlica thanks. we will log it and take a look (when ever we can get past 6.2, which is in testing...). @gregschwarz have you seen this before?
