### ISSUE TITLE
startlongtable in appendices

### ISSUE THREAD

**Issue by kbwestfall** [AASJournals/AASTeX60#74]
I have some long tables in an appendix.  The tables appear fine.  However, after the first longtable, the appendix changes from one-column to two-column format.  I assume this is a bug.  For the moment, I'm getting around this by just putting the long tables at the end of of the appendix.

**Comment by gregschwarz** [comment]
Kyle,

Which version of AASTeX are you using, 6.0, 6.1, or 6.2? If it is v6.2, can you send me the latex manuscript as an attachment at <greg.schwarz@aas.org> so I can look at it locally and reproduce the bug?

Greg

**Comment by augustfly** [comment]
If it is a bug then lets please document it here! With a MWE as necessary.

**Comment by kbwestfall** [comment]
Sorry, Greg and I worked through this off-list.  Copying from his e-mail:

> You are right in that there is a bug. It seems to me that the \startlongtable command does not reset to default number of columns after use. This is fine when used in the main portion of the manuscript with the twocolumn command but runs into problems when called in the appendix. 
>
> There is a fix for this bug and it is to use the \onecolumngrid command once you are done with the tables and ready to start with the appendix text again, e.g.
```
...
\end{deluxetable*}

\onecolumngrid
...
```
> When I put this command in the manuscript at this location all the subsequent text reverts back to a single column format.

**Comment by augustfly** [comment]
Thank you @kbwestfall for returning here to document what you and @gregschwarz found!! 

I will mark it as a bug, and leave the issue as open so that others can find this work around.
