### ISSUE TITLE
Table Appendix Labeling

### ISSUE THREAD

**Issue by augustfly** [AASJournals/AASTeX60#75]
An author asserts that old versions of AASTeX (or maybe plain article latex) could be crafted so that a Table in the appendix is labeled, "A1" etc. AASTeX v6.2 appears to prevent this labeling.

I can't confirm if this assertion is true or not or if there is a bug where the table is floating away  from the label renewcommands or if AASTeX is disabling the label or what. This definitely need more work 

Our nominal style is to **continue Table numbering from the main text into the appendix** so even if this were a bug it is a bug that acts according to our style. sort of.

**Comment by gmzsebastian** [comment]
I'm having the same problem. Adding:
```
\def\fnum@figure{Figure \Alph{section}\thefigure:}
\def\fnum@table{Table \Alph{section}\thetable:}
```
to the .cls file in the APPENDIX section fixed half the problem. The tables are now properly labelled as "A1", but the table references are not.

**Comment by augustfly** [comment]
Thanks @gmzsebastian. I was wrong above. Figure numbering is suppose to be continuous into appendices but for some reason our style permits tables/equations to be restarted with A.1 etc. Nevertheless I can't conclude that this is an intentional feature of aastex right now. Marking it as a bug to be dealt with in v6.3.
