### ISSUE TITLE
\tablebreak adds additional blank line after break

### ISSUE THREAD

**Issue by mattpitkin** [AASJournals/AASTeX60#76]
The use of `\tablebreak` to put a page break in a rotated table (specifically, in my case, a `deluxetable` in a `longrotatetable` environment) adds an extra blank line after the break. As an example, if I do:

```latex
\documentclass[twocolumn]{aastex62}

\begin{document}

\title{Test \texttt{$\backslash$tablebreak}}
\author{Matthew Pitkin}
\date{December 2018}

\startlongtable
\begin{longrotatetable}
\begin{deluxetable}{cc}
\tablehead{\colhead{a} & \colhead{b}}
\startdata
1 & 2 \\
3 & 4 \\
5 & 6 \\
7 & 8
\enddata
\end{deluxetable}
\end{longrotatetable}

\startlongtable
\begin{longrotatetable}
\begin{deluxetable}{cc}
\tablehead{\colhead{a} & \colhead{b}}
\startdata
1 & 2 \\
3 & 4 \\
\tablebreak
5 & 6 \\
7 & 8
\enddata
\end{deluxetable}
\end{longrotatetable}

\end{document}
```
I get the extra blank line after the space.

If I change the definition of the `\tablebreak` macro from

```latex
\newcommand\tablebreak{\\[-11pt]\noalign{\break}}
```

to

```latex
\newcommand\tablebreak{\\[-11pt]\noalign{\break}}
```
the line is removed. Is the blank line "supposed" to be there, or can it be removed?

Also, I think in the [docs](https://journals.aas.org/aastexguide/#tables) it should say `\tablebreak rather than `\\tablebreak`.

**Comment by augustfly** [comment]
@gregschwarz thoughts?

**Comment by augustfly** [comment]
@mattpitkin Thank you for your MWE!

Your macro edit lines are the same, but yes, i see that there is an extra `\\` in the current definition:

```
\newcommand\tablebreak{\\[-11pt]\noalign{\break}\\ }
```

which seems extraneous.  You mean this blank line marked in this image, right? I'm going to mark this as a bug for v6.3

![table_break_example2](https://user-images.githubusercontent.com/234283/50344877-f7f6ea00-04fa-11e9-97ee-204fbaf6d4fb.png)

**Comment by mattpitkin** [comment]
> You mean this blank line marked in this image, right? I'm going to mark this as a bug for v6.3

@augustfly Yep, that's that blank line I was talking about.

I know it's a small fix, but is it worth me submitting a PR for this?

**Comment by augustfly** [comment]
@mattpitkin thank you!

fixed, but leaving this open till we close all related threads for v6.3
