### ISSUE TITLE
RNAAS option puts page break before references

### ISSUE THREAD

**Issue by astrowright** [AASJournals/AASTeX60#77]
Throwing the rnaas option in the \documentclass[rnaas]{aastex62} call creates an extra page to the document containing only the references, even if there is room on the previous page to hold them.

This is a very minor issue, but it seems unintentional and has the ironic effect of adding 50-100% to the page count of Research Notes.

**Comment by gregschwarz** [comment]
I will look into this and if necessary add it to the v6.3 bug/improvements list we are currently composing. However, let me point out that the "size" of an allowable RNAAS is not dependent on the compiled pdf length at all. It is purely a word count and where those words appear on the page does not matter. Having said that, a compact pdf is always desirable.
