### ISSUE TITLE
Style of mark in tablenotetext doesn't match style of tablenotemark

### ISSUE THREAD

**Issue by metayan** [AASJournals/AASTeX60#81]
When specifying a `\tablenotemark` in a table, one typeface is used, but in the `\tablenotetext` that follows, specifying the same symbol makes it appear with a different typeface.

Even in the sample – in tables 1 and 2 – the style of the mark at the `\tablenotetext` is different from the `\tablenotemark`.

**Comment by augustfly** [comment]
very interesting @metayan -- let me inquire on our side if there's any remotely style related reason for this weirdness! @gregschwarz ?
