### ISSUE TITLE
Arxiv BibTeX have no identifier in references 

### ISSUE THREAD

**Issue by hippke** [AASJournals/AASTeX60#91]
As noted by Jason Wright: When I export a BibTeX citation for an arxiv posting using ADS and put it into AASTeX, it shows up in my paper as "ArXiv e-prints" and has no proper identifier. Any way to fix this in 6.3?

**Comment by augustfly** [comment]
Hi, thank you for this report. But it is insufficient to investigate as is. Can you please provide:  

1. the bibtex you're using;
1. which bst file you are using;
1. the output .bbl entry for the given bibtex input. 

Thank you.

**Comment by augustfly** [comment]
For example, given `aastex63.cls` and `aasjournal.bst` the following bibtex

```
@ARTICLE{2019arXiv190210103B,
       author = {{Batygin}, Konstantin and {Adams}, Fred C. and {Brown}, Michael E. and
         {Becker}, Juliette C.},
        title = "{The Planet Nine Hypothesis}",
      journal = {arXiv e-prints},
     keywords = {Astrophysics - Earth and Planetary Astrophysics},
         year = "2019",
        month = "Feb",
          eid = {arXiv:1902.10103},
        pages = {arXiv:1902.10103},
archivePrefix = {arXiv},
       eprint = {1902.10103},
 primaryClass = {astro-ph.EP},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2019arXiv190210103B},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

produces this bbl

```
\bibitem[{{Batygin} {et~al.}(2019){Batygin}, {Adams}, {Brown}, \&
  {Becker}}]{2019arXiv190210103B}
{Batygin}, K., {Adams}, F.~C., {Brown}, M.~E., \& {Becker}, J.~C. 2019, arXiv
  e-prints, arXiv:1902.10103.
\newblock \doarXiv{1902.10103}
```

See also:

```
> grep aastex test-v3.log
(/Users/aamn/Library/texmf/tex/latex/aastex63.cls
Document Class: aastex63 2019/06/03 Version 6.3/AAS markup document class
Class aastex Info: 
```
and
```
> head -3 /Users/aamn/Library/texmf/bibtex/bst/aasjournal.bst
%% AASJournal.bst June 3, 2019
%%
%% Revision 1.18 2019/6/3 Amy Hendrickson
```

**Comment by hippke** [comment]
Thanks for checking and sorry for the bug report without example. I had used the modified .bst by @seawander from [his update](https://github.com/AASJournals/AASTeX60/issues/88). The error is gone when I use the official bst file.

**Comment by augustfly** [comment]
@hippke got it. good to know! and always feel free to add any other reports or inquiries here!
