### ISSUE TITLE
Is it possible to rotate a page?

### ISSUE THREAD

**Issue by syrte** [AASJournals/AASTeX60#99]
I have a big table in paper. I realize that we can put the table in landscape through 
```
\begin{table}
\begin{rotatetable}
\begin{tabular}
...
```
however, it is a bit hard to read a landscape table.

I want to know is it possible to rotate the whole page containing the table, so that we can read the table easily. 
Or you will not recomand such treatment?

**Comment by augustfly** [comment]
Hi, thanks for asking this question.

I'm not sure I understand the context for your question. If you are preparing a preprint for your own use or for submission to us or on arXiv then you should feel free to setup your latex environment as you wish it to rotate the landscape PDF page automatically. It's your preprint. An example solution is here:

https://tex.stackexchange.com/questions/40683/rotate-single-pdf-page-when-viewing

I can't tell you if there are conflicts between this solution and aastex. Package collisions would be beyond our purview to fix as this specific request is not something we support. Again, you are free to setup your preprint as you wish.

If you are instead asking about how the final published article PDF behaves then you will need to discuss this with the IOP production office when you work with them on your page proofs. I don't know what limitations they have; they may be easily able to produce a final article PDF that has landscaped tables rotated. 

An alternative to landscape for a very wide table is to split the table into rows, e.g.

https://journals.aas.org/aastexguide/#split_table

or you can use the table cheat sheet for more options:

https://journals.aas.org/aastexguide/#table_cheat_sheet

**Comment by syrte** [comment]
@augustfly Thanks for your response.
I've tried the methods mentioned in the stackexchange website, it seems that none of them works with aastex. e.g., the `pdflscape` or `rotating` package will simply rotate the whole document instead of a single page. This is probably caused by package collisions.

So I will be satisfied with the current `rotatetable` solution.
